services:
  input_create:
    build: .
    volumes:
      - scrafiles:/app/scrafiles

  # mongo:
  #   image: mongodb/mongodb-community-server:latest
  #   ports:
  #     - 27017:27017

volumes:
  scrafiles:
    external: false